[project]
name = "src"
version = "0.1.0"
description = "Add a short description here"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
rust = ">=1.76.0,<1.77"
c-compiler = ">=1.7.0,<1.8"
llvm-tools = ">=17.0.6,<17.1"
lld = ">=17.0.6,<17.1"
openssl = ">=3.2.1,<3.3"
