package:
  name: "fusegate"
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ..
  git_rev: {{ GIT_DESCRIBE_TAG }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  host:
    - openssl

  build:
    - {{ compiler('c') }}
    - rust >=1.68
    - make
    - m4
    - lld

  run:
    - openssl

test:
  commands:
    - fusegate --help
